router setup and redirecting is done
sivasankar9/full-view-calender pull request #19
Opened 2020-05-06 16:25 UTC by manusankar9

2020-05-06 16:44 UTC, sivasankar9 commented
@manusankar9  Please fix build failure ASAP.

2020-05-06 17:14 UTC, manusankar9 commented
@sivasankar9 I've fixed build errors.

2020-05-07 01:07 UTC, sivasankar9 requested changes

2020-05-07 01:07 UTC, sivasankar9 commented on src/components/full-calender/components/shared/login/component/index.js
> +{/* <div> */ }
Remove the commented code.

2020-05-07 01:07 UTC, sivasankar9 commented on src/components/full-calender/components/shared/login/index.js
> +// const mapStateToProps = state =>  ({
clean the commented code.

2020-05-07 10:11 UTC, manusankar9 commented
@sivasankar9 I've fixed review comments

2020-05-07 10:12 UTC, manusankar9 commented on src/components/full-calender/components/shared/login/index.js
> +// const mapStateToProps = state =>  ({
removed the commented code

2020-05-07 10:52 UTC, merged