feat:created registerForm
sivasankar9/full-view-calender pull request #28
Opened 2020-05-12 12:57 UTC by manusankar9

2020-05-12 12:59 UTC, manusankar9 commented
hi @sivasankar9 ,
still working on api.

2020-05-13 16:38 UTC, sivasankar9 requested changes

2020-05-13 16:38 UTC, sivasankar9 commented on src/components/full-calender/components/shared/register-form/actions/index.js
> +		if (response) {
remove the check, it's not required.

2020-05-13 16:38 UTC, sivasankar9 commented on src/components/full-calender/components/shared/register-form/actions/index.js
> +	const payload = { username };
remove the unecessary wrapping ofr username,

2020-05-13 16:38 UTC, sivasankar9 commented on src/components/full-calender/components/shared/register-form/actions/index.js
> +		if (payload.email.length === 0) {
update to  use reg expression.

2020-05-13 16:38 UTC, sivasankar9 commented on src/components/full-calender/components/shared/register-form/actions/index.js
> +		const isError = !payload.length > 0;
please use utility  reg and rename the const **isError** to  _error_

2020-05-13 16:38 UTC, sivasankar9 commented on src/components/full-calender/components/shared/register-form/index.js
> +export default connect(mapStateToProps, {registerUserDetails,passwordAvailabilityReset, userAvailability, userAvailabilityReset, emailAvailabilityReset, emailAvailability, passwordAvailability})(Regi
create a const actions = { }  drop all the actions in it.

2020-05-13 16:38 UTC, sivasankar9 commented on src/components/full-calender/components/shared/register-form/reducer/password.js
> +        case "RESET_PASSWORD_DATA": return initialState;
it should be ...
        case "RESET_PASSWORD_DATA":
        case "RESET_REGISTER_FORM":
                  return initialState;

2020-05-13 16:38 UTC, sivasankar9 commented on src/components/full-calender/components/shared/register-form/reducer/usename.js
> +        case "USER_AVAILABILITY_DATA":return action.payload;
it should be ...
case "RESET_USERNAME_DATA":
case "RESET_REGISTER_FORM":
return initialState;

2020-05-13 16:38 UTC, sivasankar9 commented on src/index.js
>  import calenderEvents from './components/full-calender/reducer';
import should be **fullCalender**

2020-05-13 16:38 UTC, sivasankar9 commented on src/index.js
> +    loginCalender: loginCalender,
it should be only
 **loginCalender**,
**registerFormCalender**

2020-05-13 16:38 UTC, sivasankar9 commented on src/components/full-calender/components/shared/register-form/component/index.js
> +    if (e.target.value !== "") {
use util function.

2020-05-13 16:38 UTC, sivasankar9 commented on src/components/full-calender/components/shared/register-form/component/index.js
> +    if (e.target.value !== "") {
use util function.

2020-05-13 16:38 UTC, sivasankar9 commented on src/components/full-calender/components/shared/register-form/component/index.js
> +    if (e.target.value !== "") {
use util function.

2020-05-13 16:38 UTC, sivasankar9 commented on src/components/full-calender/components/shared/register-form/component/index.js
> +    let flg = [!emailError, !passwordError, !usernameError].every(a => a);
update flg to const isButtonEnable.

2020-05-14 04:04 UTC, sivasankar9 approved these changes

2020-05-14 04:05 UTC, merged